include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**, lib/jellyfin/**]
  language:
    # strict-casts: false
    # strict-raw-types: true
  plugins:
    - custom_lint

linter:
  rules:
    cancel_subscriptions: true
    avoid_print: false # Uncomment to disable the `avoid_print` rule
    no_logic_in_create_state: true
    # prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    eol_at_end_of_file: true
