targets:
  $default:
    sources:
      - lib/$lib$
      - "**/models/**.dart" # Matches models folder at any depth in lib
      - "**/providers/**.dart" # Matches providers folder at any depth in lib
      - lib/util/**.dart
      - lib/jellyfin/**.dart
      - swagger/**
      - $package$
    builders:
      freezed|freezed:
        options:
          generate_for:
            - "**/**.f.dart"
            - "**/**.g.dart"
      dart_mappable_builder:
        options:
          ignoreNull: true
          discriminatorKey: type
          generateMethods: [decode, encode, copy, stringify]
      swagger_dart_code_generator:
        options:
          input_folder: "swagger/"
          output_folder: "lib/jellyfin/"
          with_converter: true
          build_only_models: false
          with_base_url: false
          include_if_null: false
          auto_apply: dependents
      chopper_generator:
        options:
          header: "//Generated jellyfin api code"
          include_if_null: false
